# Generated by Django 4.2.5 on 2023-09-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "demo_service",
            "0002_rename_photourl_pet_photo_url_petcategory_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="petcategory",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
