# Generated by Django 4.2.5 on 2023-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_service", "0003_alter_pet_name_alter_petcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=30,
            ),
        ),
    ]
